apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground # c'est le nom qu'on a donné au label de l'application dans le Deployment
  ports:
    - port: 8888       # Le port exposé par ce Service
      targetPort: 8888 # Le port du conteneur défini dans le Deployment
  type: ClusterIP