FROM nginx:alpine

COPY index.html /usr/share/nginx/html/

EXPOSE 80

# Build and run the Docker container:
# cd test_docker
# docker build -t test-nginx .
# docker run -d -p 8080:80 --name web-nginx test-nginx